### ISSUE TITLE
How do I enable this plugin?

### ISSUE THREAD

**Issue by ghost** [sublimelsp/LSP-bash#70]
This is my LSP.sublime-settings that I use to enable lsp-clangd plugin
```
// Settings in here override those in "LSP/LSP.sublime-settings"
{
  "inhibit_snippet_completions": true,
  "show_view_status": false,
  "clients": {
    "clangd": {
      "enabled": true,
      "command": [
        "clangd", // you may use an absolute path for this clangd executable
        "-function-arg-placeholders=0",
        "-header-insertion-decorators=1",
        "-background-index",
        "-j=3",
      ],
      "scopes": ["source.c", "source.c++", "source.objc", "source.objc++"],
      "syntaxes": [
        "Packages/C++/C.sublime-syntax",
        "Packages/C++/C++.sublime-syntax",
        "Packages/Objective-C/Objective-C.sublime-syntax",
        "Packages/Objective-C/Objective-C++.sublime-syntax",
      ],
      "languageId": "cpp",
    }
  }
}
```

**Comment by jfcherng** [comment]
it just work. it sounds like yoi didnt install this plugin.

**Comment by jfcherng** [comment]
To be clear, I actually recommend let LSP/lsp-utils/LSP-* manage everything they need so that there is no enviroment differences among users. Fwiw, your `bash-completion-server` won't be used unless you deliberately modified the settings.

The first thing you can do is to run the troubleshooting and post the text result here.
![image](https://github.com/sublimelsp/LSP-bash/assets/6594915/112532c4-6c60-430e-b249-acd9e5512ee7)

**Comment by jfcherng** [comment]
> I had to install shellcheck for the linting to get enabled. @jfcherng

Hmm... actually, I think we can have LSP-bash handled this but currently it's not.
